habits_and_goals_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("tracker.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/urls.py
from django.urls import path

from tracker.views import (
    GoalListView,
    GoalCreateView,
    GoalDetailView,
    GoalStageCreateView,
    HabitListView,
    HabitCreateView,
    HabitDetailView,
    CommentaryGoalCreateView,
    CommentaryHabitCreateView,
    GoalDeleteView,
    GoalUpdateView,
    GoalStageUpdateView,
    GoalStageDeleteView,
    HabitDeleteView,
    HabitUpdateView,
    IndexView,
    GoalToggleStatusView,
    GoalToggleAbandonedStatusView,
    GoalToggleStageStatusView,
    GoalToggleStageAbandonedStatusView
)

app_name = "tracker"

urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index"
    ),
    path(
        "goals/",
        GoalListView.as_view(),
        name="goal-list"
    ),
    path(
        "goals/create/",
        GoalCreateView.as_view(),
        name="goal-create"
    ),
    path(
        "goals/<int:pk>/",
        GoalDetailView.as_view(),
        name="goal-detail"
    ),
    path(
        "goals/<int:pk>/delete",
        GoalDeleteView.as_view(),
        name="goal-delete"
    ),
    path(
        "goals/<int:pk>/update",
        GoalUpdateView.as_view(),
        name="goal-update"
    ),
    path(
        "goals/<int:pk>/toggle/",
        GoalToggleStatusView.as_view(),
        name="goal-update-status"
    ),
    path(
        "goals/<int:pk>/toggle/abandoned/",
        GoalToggleAbandonedStatusView.as_view(),
        name="goal-update-status-abandoned"
    ),
    path(
        "goals/<int:goal_id>/create/stage/",
        GoalStageCreateView.as_view(),
        name="goal-create-stage"
    ),
    path(
        "goals/<int:goal_id>/update/stage/<int:pk>/",
        GoalStageUpdateView.as_view(),
        name="goal-update-stage"
    ),
    path(
        "goals/<int:goal_id>/delete/stage/<int:pk>/",
        GoalStageDeleteView.as_view(),
        name="goal-delete-stage"
    ),
    path(
        "goals/<int:goal_id>/toggle/<int:pk>/",
        GoalToggleStageStatusView.as_view(),
        name="goal-update-stage-status"
    ),
    path(
        "goals/<int:goal_id>/toggle/<int:pk>/abandoned/",
        GoalToggleStageAbandonedStatusView.as_view(),
        name="goal-update-stage-status-abandoned"
    ),
    path(
        "goals/<int:pk>/create/commentary/",
        CommentaryGoalCreateView.as_view(),
        name="goal-commentary-create"
    ),
    path(
        "habits/",
        HabitListView.as_view(),
        name="habit-list"
    ),
    path(
        "habits/create/",
        HabitCreateView.as_view(),
        name="habit-create"
    ),
    path(
        "habits/<int:pk>/delete/",
        HabitDeleteView.as_view(),
        name="habit-delete"
    ),
    path(
        "habits/<int:pk>/update/",
        HabitUpdateView.as_view(),
        name="habit-update"
    ),
    path(
        "habits/<int:pk>/",
        HabitDetailView.as_view(),
        name="habit-detail"
    ),
    path(
        "habits/<int:pk>/create/commentary/",
        CommentaryHabitCreateView.as_view(),
        name="habit-commentary-create"
    ),
    path(
        "habits/<int:pk>/create/log/",
        CommentaryHabitCreateView.as_view(),
        name="habit-commentary-create"
    ),
]

templates/habit/habit_commentary_form.html
{% extends "base.html" %}

{% block content %}
  <form method="post" action="{% url "tracker:habit-commentary-create" pk=habit_id %}">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Create comment">
  </form>
{% endblock %}

templates/habit/habit_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Habit?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <button type="button" onclick="goBack()" class="btn btn-secondary">No, go back</button>
  </form>


  <script>
      function goBack() {
          window.history.back();
      }
  </script>
{% endblock %}

templates/habit/habit_day_completion_form.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ object|yesno:"Update, Create" }} habit status
  </h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/habit/habit_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="card bg-light p-4 border border-secondary" style="width: 70%; margin: 0 auto; border-radius: 30px">
    <div class="card-body">
      <div class="d-flex align-items-center mb-3">
        <h1 class="mr-3">{{ habit.name }}</h1>
        <a href="{% url "tracker:habit-update" pk=habit.id %}" class="btn btn-outline-secondary btn-sm mr-2">
          ✏️ Edit
        </a>
        <a href="{% url "tracker:habit-delete" pk=habit.id %}" class="btn btn-outline-danger btn-sm">
          🗑️ Delete
        </a>
      </div>
      <p class="mb-4"><strong>Start:</strong> {{ habit.created_at }}</p>
      <h4 class="mb-3">Description:</h4>
      <p>{{ habit.description }}</p>
      <h3 class="mt-5 mb-3">Month Goal:</h3>
      <div class="d-flex align-items-center">
        <i class="bi bi-check2-square fs-3 text-success mr-3"></i>
        <p class="mb-0">{{ habit.month_goal }}</p>
      </div>
    </div>
  </div>


  {% if today_date not in filled_dates %}

    <div class="card mt-5">
      <div class="card-body">
        <h5 class="card-title">Have you completed the habit today?</h5>
        <form method="POST" action="{% url "tracker:habit-detail" pk=habit.pk %}">
          {% csrf_token %}
          {{ habit_log_form.as_p }}
          <input type="submit" value="Submit" class="btn btn-primary">
        </form>
      </div>
    </div>
  {% endif %}
  <br><br>

  <div class="habit-statistic">
    <div class="row">
      <div class="col-md-6">

        <div class="mt-3">
          <table class="table table-bordered" style="width: 80%;">
            <thead class="thead-dark text-white" style="background-color: #C0C0C0;">
            <tr>
              <th colspan="2">
                <h2>Completion history:</h2>
              </th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td>Total days from start</td>
              <td>{{ total_days }}</td>
            </tr>
            <tr>
              <td>Days completed</td>
              <td>{{ completed_days_log }}</td>
            </tr>
            <tr>
              <td>Days ignored</td>
              <td>{{ ignored_days }}</td>
            </tr>
            <tr>
              <td>Days passed</td>
              <td>{{ not_completed_days_log }}</td>
            </tr>
            <tr>
              <td>Focus %</td>
              <td>{{ progress_percent }}%</td>
            </tr>
            </tbody>
          </table>
          <div class="progress" style="height: 20px; width: 30%;">
            <div class="progress-bar bg-success" role="progressbar" style="width: {{ progress_percent }}%;"
                 aria-valuenow="{{ progress_percent }}" aria-valuemin="0" aria-valuemax="100">
              <span class="sr-only">{{ progress_percent }}% focus</span>
            </div>
          </div>
        </div>

        <br>

        <ul>
          {% for log in habit.logs.all %}
            {% if log.completed %}
              <li>{{ log }} - ✔️</li>
            {% else %}
              <li>{{ log }} - ❌</li>

            {% endif %}
          {% empty %}
            <li>No logs for this habit.</li>
          {% endfor %}

        </ul>

      </div>
      <div class="col-md-6">
        <h3>Leave a Comment</h3>
        <form method="POST" action="{% url "tracker:habit-commentary-create" pk=habit.pk %}" class="form">
          {% csrf_token %}
          <div class="form-group">
            {{ commentary_form.text|as_crispy_field }}
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <br>
        <div style="text-align: center">
          <h3>Comment Zone:</h3>
        </div>
        <ul class="list-group list-group-flush">
          {% for comment in habit_commentaries %}
            <li class="list-group-item">
              <h4>{{ comment.text }}</h4>
              <small>(Comment by: {{ comment.user }}
                at {{ comment.created_at.time }} {{ comment.created_at.date }})</small>
            </li>
          {% empty %}
            <li class="list-group-item">No comments yet.</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/habit/habit_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    {{ object|yesno:"Update, Create" }} habit
  </h1>
  <div class="left-right-margin-add" style="width: 50%">
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}

templates/habit/habit_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="d-flex justify-content-center align-items-center flex-column">
    <h1 class="text-center mb-5">Habit List</h1>

    <form action="" method="get">
      <div class="form-group">
        <div class="input-group">
          {{ search_form|crispy }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-primary">🔍</button>
          </div>
        </div>
      </div>
    </form>

    <a href="{% url 'tracker:habit-create' %}" class="btn btn-primary mb-3">
      Create a new habit
    </a>
  </div>

  <ul class="list-unstyled">
    {% for habit in habit_list %}
      <li class="border rounded p-3 mb-3">
        <div class="d-flex justify-content-between align-items-center">
          <h3 class="m-0"><a href="{% url "tracker:habit-detail" pk=habit.id %}"
                             class="text-decoration-none">{{ habit.name }}</a></h3>
        </div>
        <p class="mt-3">{{ habit.description }}</p>
      </li>
    {% endfor %}
  </ul>
{% endblock %}