habits_and_goals_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("tracker.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/urls.py
from django.urls import path

from tracker.views import (
    GoalListView,
    GoalCreateView,
    GoalDetailView,
    GoalStageCreateView,
    HabitListView,
    HabitCreateView,
    HabitDetailView,
    CommentaryGoalCreateView,
    CommentaryHabitCreateView,
    GoalDeleteView,
    GoalUpdateView,
    GoalStageUpdateView,
    GoalStageDeleteView,
    HabitDeleteView,
    HabitUpdateView,
    IndexView,
    GoalToggleStatusView,
    GoalToggleAbandonedStatusView,
    GoalToggleStageStatusView,
    GoalToggleStageAbandonedStatusView
)

app_name = "tracker"

urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index"
    ),
    path(
        "goals/",
        GoalListView.as_view(),
        name="goal-list"
    ),
    path(
        "goals/create/",
        GoalCreateView.as_view(),
        name="goal-create"
    ),
    path(
        "goals/<int:pk>/",
        GoalDetailView.as_view(),
        name="goal-detail"
    ),
    path(
        "goals/<int:pk>/delete",
        GoalDeleteView.as_view(),
        name="goal-delete"
    ),
    path(
        "goals/<int:pk>/update",
        GoalUpdateView.as_view(),
        name="goal-update"
    ),
    path(
        "goals/<int:pk>/toggle/",
        GoalToggleStatusView.as_view(),
        name="goal-update-status"
    ),
    path(
        "goals/<int:pk>/toggle/abandoned/",
        GoalToggleAbandonedStatusView.as_view(),
        name="goal-update-status-abandoned"
    ),
    path(
        "goals/<int:goal_id>/create/stage/",
        GoalStageCreateView.as_view(),
        name="goal-create-stage"
    ),
    path(
        "goals/<int:goal_id>/update/stage/<int:pk>/",
        GoalStageUpdateView.as_view(),
        name="goal-update-stage"
    ),
    path(
        "goals/<int:goal_id>/delete/stage/<int:pk>/",
        GoalStageDeleteView.as_view(),
        name="goal-delete-stage"
    ),
    path(
        "goals/<int:goal_id>/toggle/<int:pk>/",
        GoalToggleStageStatusView.as_view(),
        name="goal-update-stage-status"
    ),
    path(
        "goals/<int:goal_id>/toggle/<int:pk>/abandoned/",
        GoalToggleStageAbandonedStatusView.as_view(),
        name="goal-update-stage-status-abandoned"
    ),
    path(
        "goals/<int:pk>/create/commentary/",
        CommentaryGoalCreateView.as_view(),
        name="goal-commentary-create"
    ),
    path(
        "habits/",
        HabitListView.as_view(),
        name="habit-list"
    ),
    path(
        "habits/create/",
        HabitCreateView.as_view(),
        name="habit-create"
    ),
    path(
        "habits/<int:pk>/delete/",
        HabitDeleteView.as_view(),
        name="habit-delete"
    ),
    path(
        "habits/<int:pk>/update/",
        HabitUpdateView.as_view(),
        name="habit-update"
    ),
    path(
        "habits/<int:pk>/",
        HabitDetailView.as_view(),
        name="habit-detail"
    ),
    path(
        "habits/<int:pk>/create/commentary/",
        CommentaryHabitCreateView.as_view(),
        name="habit-commentary-create"
    ),
    path(
        "habits/<int:pk>/create/log/",
        CommentaryHabitCreateView.as_view(),
        name="habit-commentary-create"
    ),
]

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ user.get_absolute_url }}">{{ user.get_username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
      </li>
    </ul>
  {% else %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Login</a>
      </li>
    </ul>
  {% endif %}


  <ul class="navbar-nav mx-auto">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'tracker:index' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'tracker:goal-list' %}">My Goals</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'tracker:habit-list' %}">My Habits</a>
    </li>
  </ul>

</nav>
<br>