habits_and_goals_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("tracker.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/urls.py
from django.urls import path

from tracker.views import (
    GoalListView,
    GoalCreateView,
    GoalDetailView,
    GoalStageCreateView,
    HabitListView,
    HabitCreateView,
    HabitDetailView,
    CommentaryGoalCreateView,
    CommentaryHabitCreateView,
    GoalDeleteView,
    GoalUpdateView,
    GoalStageUpdateView,
    GoalStageDeleteView,
    HabitDeleteView,
    HabitUpdateView,
    IndexView,
    GoalToggleStatusView,
    GoalToggleAbandonedStatusView,
    GoalToggleStageStatusView,
    GoalToggleStageAbandonedStatusView
)

app_name = "tracker"

urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index"
    ),
    path(
        "goals/",
        GoalListView.as_view(),
        name="goal-list"
    ),
    path(
        "goals/create/",
        GoalCreateView.as_view(),
        name="goal-create"
    ),
    path(
        "goals/<int:pk>/",
        GoalDetailView.as_view(),
        name="goal-detail"
    ),
    path(
        "goals/<int:pk>/delete",
        GoalDeleteView.as_view(),
        name="goal-delete"
    ),
    path(
        "goals/<int:pk>/update",
        GoalUpdateView.as_view(),
        name="goal-update"
    ),
    path(
        "goals/<int:pk>/toggle/",
        GoalToggleStatusView.as_view(),
        name="goal-update-status"
    ),
    path(
        "goals/<int:pk>/toggle/abandoned/",
        GoalToggleAbandonedStatusView.as_view(),
        name="goal-update-status-abandoned"
    ),
    path(
        "goals/<int:goal_id>/create/stage/",
        GoalStageCreateView.as_view(),
        name="goal-create-stage"
    ),
    path(
        "goals/<int:goal_id>/update/stage/<int:pk>/",
        GoalStageUpdateView.as_view(),
        name="goal-update-stage"
    ),
    path(
        "goals/<int:goal_id>/delete/stage/<int:pk>/",
        GoalStageDeleteView.as_view(),
        name="goal-delete-stage"
    ),
    path(
        "goals/<int:goal_id>/toggle/<int:pk>/",
        GoalToggleStageStatusView.as_view(),
        name="goal-update-stage-status"
    ),
    path(
        "goals/<int:goal_id>/toggle/<int:pk>/abandoned/",
        GoalToggleStageAbandonedStatusView.as_view(),
        name="goal-update-stage-status-abandoned"
    ),
    path(
        "goals/<int:pk>/create/commentary/",
        CommentaryGoalCreateView.as_view(),
        name="goal-commentary-create"
    ),
    path(
        "habits/",
        HabitListView.as_view(),
        name="habit-list"
    ),
    path(
        "habits/create/",
        HabitCreateView.as_view(),
        name="habit-create"
    ),
    path(
        "habits/<int:pk>/delete/",
        HabitDeleteView.as_view(),
        name="habit-delete"
    ),
    path(
        "habits/<int:pk>/update/",
        HabitUpdateView.as_view(),
        name="habit-update"
    ),
    path(
        "habits/<int:pk>/",
        HabitDetailView.as_view(),
        name="habit-detail"
    ),
    path(
        "habits/<int:pk>/create/commentary/",
        CommentaryHabitCreateView.as_view(),
        name="habit-commentary-create"
    ),
    path(
        "habits/<int:pk>/create/log/",
        CommentaryHabitCreateView.as_view(),
        name="habit-commentary-create"
    ),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% block title %}
    <title>Goals | Habit tracker</title>
    <link rel="icon" href="{% static 'images/favicon-16x16.png' %}">
  {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossorigin="anonymous"></script>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
{% block sidebar %}
  {% include "includes/sidebar.html" %}
{% endblock %}

{% block content %}
{% endblock %}

{% block pagination %}
  {% include "includes/pagination.html" %}

{% endblock %}

{% block scripts %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
      $(function () {
          $('input[type="datetime-local"]').attr('step', '1');
      });
  </script>
{% endblock %}
</body>
</html>

templates/commentary_form.html
{% extends "base.html" %}

{% block content %}
  <form method="post" action="{% url "tracker:goal-commentary-create" pk=goal_id%}">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Create comment">
  </form>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
  <div style="text-align: center;">
    <h1>You have {{ total_goals_number }} goals:</h1>
  </div>

  <br>
  <div class="goal-container">
    <div class="goal">
      <p class="goal-title">
        Active Goals:
        <a href="{% url "tracker:goal-list" %}?status=active">View all({{ active_goals_number }})</a>
      </p>
      <div class="progress-bar-container">
        <div class="progress-bar progress-bar-striped progress-bar-animated"
             style="width: {{ active_goals_percent }}%;">
          {{ active_goals_percent }}%
        </div>
      </div>
    </div>

    <div class="goal">
      <p class="goal-title">
        Abandoned Goals:
        <a href="{% url "tracker:goal-list" %}?status=abandoned">View all({{ abandoned_goals_number }})</a>
      </p>
      <div class="progress-bar-container">
        <div class="progress-bar progress-bar-striped progress-bar-animated"
             style="width: {{ abandoned_goals_percent }}%;">
          {{ abandoned_goals_percent }}%
        </div>
      </div>
    </div>

    <div class="goal">
      <p class="goal-title">
        Completed Goals:
        <a href="{% url "tracker:goal-list" %}?status=completed">View all({{ completed_goals_number }})</a>
      </p>
      <div class="progress-bar-container">
        <div class="progress-bar progress-bar-striped progress-bar-animated"
             style="width: {{ completed_goals_percent }}%;">
          {{ completed_goals_percent }}%
        </div>
      </div>
    </div>
  </div>
  <br><br>

  <div style="text-align: center;">
    <h1>You have {{ habits_number }} habits:</h1>
  </div>
  <br>
  <div class="table-responsive" style="width: 70%; margin: 0 auto;">
    <table class="table table-bordered table-hover table-striped" style="margin: 0 auto;">
      <thead class="bg-dark text-white">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Month Goal</th>
        <th>Start Date</th>
      </tr>
      </thead>
      <tbody>
      {% for habit in habits_objects %}
        <tr>
          <td><a href="{% url "tracker:habit-detail" pk=habit.pk %}" class="text-decoration-none">{{ habit.name }}</a>
          </td>
          <td>{{ habit.description }}</td>
          <td>{{ habit.month_goal }}</td>
          <td>{{ habit.created_at.date }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}