habits_and_goals_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("tracker.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/urls.py
from django.urls import path

from tracker.views import (
    GoalListView,
    GoalCreateView,
    GoalDetailView,
    GoalStageCreateView,
    HabitListView,
    HabitCreateView,
    HabitDetailView,
    CommentaryGoalCreateView,
    CommentaryHabitCreateView,
    GoalDeleteView,
    GoalUpdateView,
    GoalStageUpdateView,
    GoalStageDeleteView,
    HabitDeleteView,
    HabitUpdateView,
    IndexView,
    GoalToggleStatusView,
    GoalToggleAbandonedStatusView,
    GoalToggleStageStatusView,
    GoalToggleStageAbandonedStatusView
)

app_name = "tracker"

urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index"
    ),
    path(
        "goals/",
        GoalListView.as_view(),
        name="goal-list"
    ),
    path(
        "goals/create/",
        GoalCreateView.as_view(),
        name="goal-create"
    ),
    path(
        "goals/<int:pk>/",
        GoalDetailView.as_view(),
        name="goal-detail"
    ),
    path(
        "goals/<int:pk>/delete",
        GoalDeleteView.as_view(),
        name="goal-delete"
    ),
    path(
        "goals/<int:pk>/update",
        GoalUpdateView.as_view(),
        name="goal-update"
    ),
    path(
        "goals/<int:pk>/toggle/",
        GoalToggleStatusView.as_view(),
        name="goal-update-status"
    ),
    path(
        "goals/<int:pk>/toggle/abandoned/",
        GoalToggleAbandonedStatusView.as_view(),
        name="goal-update-status-abandoned"
    ),
    path(
        "goals/<int:goal_id>/create/stage/",
        GoalStageCreateView.as_view(),
        name="goal-create-stage"
    ),
    path(
        "goals/<int:goal_id>/update/stage/<int:pk>/",
        GoalStageUpdateView.as_view(),
        name="goal-update-stage"
    ),
    path(
        "goals/<int:goal_id>/delete/stage/<int:pk>/",
        GoalStageDeleteView.as_view(),
        name="goal-delete-stage"
    ),
    path(
        "goals/<int:goal_id>/toggle/<int:pk>/",
        GoalToggleStageStatusView.as_view(),
        name="goal-update-stage-status"
    ),
    path(
        "goals/<int:goal_id>/toggle/<int:pk>/abandoned/",
        GoalToggleStageAbandonedStatusView.as_view(),
        name="goal-update-stage-status-abandoned"
    ),
    path(
        "goals/<int:pk>/create/commentary/",
        CommentaryGoalCreateView.as_view(),
        name="goal-commentary-create"
    ),
    path(
        "habits/",
        HabitListView.as_view(),
        name="habit-list"
    ),
    path(
        "habits/create/",
        HabitCreateView.as_view(),
        name="habit-create"
    ),
    path(
        "habits/<int:pk>/delete/",
        HabitDeleteView.as_view(),
        name="habit-delete"
    ),
    path(
        "habits/<int:pk>/update/",
        HabitUpdateView.as_view(),
        name="habit-update"
    ),
    path(
        "habits/<int:pk>/",
        HabitDetailView.as_view(),
        name="habit-detail"
    ),
    path(
        "habits/<int:pk>/create/commentary/",
        CommentaryHabitCreateView.as_view(),
        name="habit-commentary-create"
    ),
    path(
        "habits/<int:pk>/create/log/",
        CommentaryHabitCreateView.as_view(),
        name="habit-commentary-create"
    ),
]

templates/goal/goal_commentary_form.html
{% extends "base.html" %}

{% block content %}
  <form method="post" action="{% url "tracker:goal-commentary-create" pk=goal_id %}">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Create comment">
  </form>
{% endblock %}

templates/goal/goal_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Goal?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <button type="button" onclick="goBack()" class="btn btn-secondary">No, go back</button>
  </form>


  <script>
      function goBack() {
          window.history.back();
      }
  </script>
{% endblock %}

templates/goal/goal_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="d-flex justify-content-center align-items-center flex-column">
    <div class="row align-items-center">
      <div class="col">
        <h1>{{ goal.name }}</h1>
      </div>
      <div class="col-auto">
        <div class="btn-group">
          <a href="{% url 'tracker:goal-update' pk=goal.id %}" class="btn btn-outline-secondary btn-sm mr-2">
            ✏️
          </a>
          <a href="{% url 'tracker:goal-delete' pk=goal.id %}" class="btn btn-outline-danger btn-sm">
            🗑️
          </a>
        </div>
      </div>
    </div>
    {{ goal.description }}
    <br>
    <strong style="color: darkred">Deadline: {{ goal.deadline.date }}</strong>
    <br>

    {% if goal.status == 'active' %}

      <div class="btn btn-success">
        {{ goal.status }}
        <button type="button" class="btn btn-sm btn-danger"
                onclick="document.location.href='{% url 'tracker:goal-update-status' pk=goal.pk %}'">
          Mark as Done
        </button>
      </div>
      <br>
      <div class="btn btn-secondary">
        <button type="button" class="btn btn-sm btn-secondary"
                onclick="document.location.href='{% url 'tracker:goal-update-status-abandoned' pk=goal.pk %}'">
          Abandon goal
        </button>
      </div>
    {% elif goal.status == 'abandoned' %}

      <div class="btn btn-secondary">
        {{ goal.status }}
        <button type="button" class="btn btn-sm btn-success"
                onclick="document.location.href='{% url 'tracker:goal-update-status-abandoned' pk=goal.pk %}'">
          Reactive goal
        </button>
      </div>
    {% else %}

      <div class="btn btn-danger">
        {{ goal.status }}
        <button type="button" class="btn btn-sm btn-success"
                onclick="document.location.href='{% url 'tracker:goal-update-status' pk=goal.pk %}'">
          Reactive goal
        </button>
      </div>
    {% endif %}
  </div>
  <br><br>

  <div class="left-right-margin-add">
    <a href="{% url "tracker:goal-create-stage" goal_id=goal.id %}" class="btn btn-primary">
      Create new stage
    </a>
    <br><br>
    <div class="card">
      <ul class="list-group list-group-flush">
        {% for stage in goal_stages %}
          <li class="list-group-item">
            <div class="d-flex justify-content-between align-items-center">
              {% if stage.status == "active" %}
                <h3 class="mb-0">{{ stage.stage_name }}</h3>
              {% else %}
                <h3 class="mb-0 text-muted">
                  <del>{{ stage.stage_name }}</del>
                </h3>
              {% endif %}
              <div>
                <a href="{% url "tracker:goal-update-stage" pk=stage.pk goal_id=goal.id %}"
                   class="btn btn-secondary mr-2">
                  ️✏️
                </a>
                <a href="{% url "tracker:goal-delete-stage" pk=stage.pk goal_id=goal.id %}" class="btn btn-danger">
                  🗑️
                </a>
              </div>
            </div>
            <div class="d-flex justify-content-between align-items-center mt-2">
              {% if stage.status == "active" %}
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-sm btn-success mr-2"
                          onclick="document.location.href='{% url "tracker:goal-update-stage-status" goal_id=goal.id pk=stage.id %}'">
                    Done
                  </button>
                  <button type="button" class="btn btn-sm btn-secondary"
                          onclick="document.location.href='{% url "tracker:goal-update-stage-status-abandoned" goal_id=goal.id pk=stage.id %}'">
                    Abandon
                  </button>
                </div>
              {% elif stage.status == "abandoned" %}
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-sm btn-secondary"
                          onclick="document.location.href='{% url "tracker:goal-update-stage-status-abandoned" goal_id=goal.id pk=stage.id %}'">
                    Reactivate
                  </button>
                </div>
              {% else %}
                <div class="btn-group" role="group">
                  <button type="button" class="btn btn-sm btn-danger"
                          onclick="document.location.href='{% url "tracker:goal-update-stage-status" goal_id=goal.id pk=stage.id %}'">
                    Reactivate
                  </button>
                </div>
              {% endif %}
              <div class="text-muted">
                start: {{ stage.created_at }}
                <br>
                deadline: {{ stage.deadline.date }}
              </div>
            </div>
            <div class="mt-2">
              {{ stage.description }}
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>

    <br><br>

    <div class="row">
      <div class="col-md-6">
        <h3>Leave a Comment</h3>
        <form method="POST" action="{% url 'tracker:goal-commentary-create' pk=goal.pk %}" class="form">
          {% csrf_token %}
          <div class="form-group">
            {{ form.text|as_crispy_field }}
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
      <div class="col-md-6">
        <div style="text-align: center">
          <h3>Comment Zone:</h3>
        </div>
        <ul class="list-group list-group-flush">
          {% for comment in goal_commentaries %}
            <li class="list-group-item">
              <h4>{{ comment.text }}</h4>
              <small>(Comment by: {{ comment.user }}
                at {{ comment.created_at.time }} {{ comment.created_at.date }})</small>
            </li>
          {% empty %}
            <li class="list-group-item">No comments yet.</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/goal/goal_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    {{ object|yesno:"Update, Create" }} goal
  </h1>
  <div class="left-right-margin-add" style="width: 50%">
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}

templates/goal/goal_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="d-flex justify-content-center align-items-center flex-column">
    <h1 class="text-center mb-5">Goal List</h1>

    <form action="" method="get">
      <div class="form-group">
        <div class="input-group">
          {{ search_form|crispy }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-primary">🔍</button>
          </div>
        </div>
      </div>
      {% if request.GET.status %}
        <input type="hidden" name="status" value="{{ request.GET.status }}">
      {% endif %}
      {% if request.GET.query %}
        <input type="hidden" name="query" value="{{ request.GET.query }}">
      {% endif %}
    </form>
    <br>

    <a href="{% url 'tracker:goal-create' %}" class="btn btn-primary mb-3">Create a new goal</a>
  </div>
  <form method="get" class="d-flex align-items-center" style="width: 15%; margin-left: 1%">
    <label for="status" class="me-3">Status:</label>
    <select name="status" id="status" class="form-select me-3">
      <option value="">All</option>
      <option value="active" {% if request.GET.status == "active" %}selected{% endif %}>Active</option>
      <option value="completed" {% if request.GET.status == "completed" %}selected{% endif %}>Completed</option>
      <option value="abandoned" {% if request.GET.status == "abandoned" %}selected{% endif %}>Abandoned</option>
    </select>
    <button type="submit" class="btn btn-primary">Filter</button>
  </form>
  <br>

  {% if goal_list %}
    <ul class="list-unstyled">
      {% for goal in goal_list %}
        <li class="border rounded p-3 mb-3">
          <div class="d-flex justify-content-between align-items-center">
            <h3 class="m-0"><a href="{% url "tracker:goal-detail" pk=goal.id %}"
                               class="text-decoration-none">{{ goal.name }}</a></h3>
            {% if goal.status == "active" %}
              <span class="badge badge-primary">Active</span>
            {% elif goal.status == "completed" %}
              <span class="badge badge-success">Completed</span>
            {% else %}
              <span class="badge badge-danger">Abandoned</span>
            {% endif %}
          </div>
          <p class="mt-3">{{ goal.description }}</p>
          <p class="mb-0"><strong>Deadline:</strong> {{ goal.deadline.date }}</p>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No goals found.</p>
  {% endif %}

{% endblock %}

templates/goal/goal_list_abandoned.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align: center">
    Abandoned goals:
  </h1>

  <br>
  {% if goal_list_abandoned %}
    <ul class="list-unstyled">
      {% for goal in goal_list_abandoned %}
        <li class="border rounded p-3 mb-3">
          <div class="d-flex justify-content-between align-items-center">
            <h3 class="m-0"><a href="{% url "tracker:goal-detail" pk=goal.id %}"
                               class="text-decoration-none">{{ goal.name }}</a></h3>
          </div>
          <p class="mt-3">{{ goal.description }}</p>
          <p class="mb-0"><strong>Deadline:</strong> {{ goal.deadline.date }}</p>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No goals found.</p>
  {% endif %}

{% endblock %}

templates/goal/goal_list_active.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align: center">
    Active goals:
  </h1>

  {% if goal_list_active %}
    <ul class="list-unstyled">
      {% for goal in goal_list_active %}
        <li class="border rounded p-3 mb-3">
          <div class="d-flex justify-content-between align-items-center">
            <h3 class="m-0"><a href="{% url "tracker:goal-detail" pk=goal.id %}"
                               class="text-decoration-none">{{ goal.name }}</a></h3>
          </div>
          <p class="mt-3">{{ goal.description }}</p>
          <p class="mb-0"><strong>Deadline:</strong> {{ goal.deadline.date }}</p>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No goals found.</p>
  {% endif %}

{% endblock %}

templates/goal/goal_list_completed.html
{% extends "base.html" %}

{% block content %}

  <h1 style="text-align: center">
    Completed goals:
  </h1>

  {% if goal_list_completed %}
    <ul class="list-unstyled">
      {% for goal in goal_list_completed %}
        <li class="border rounded p-3 mb-3">
          <div class="d-flex justify-content-between align-items-center">
            <h3 class="m-0"><a href="{% url "tracker:goal-detail" pk=goal.id %}"
                               class="text-decoration-none">{{ goal.name }}</a></h3>
          </div>
          <p class="mt-3">{{ goal.description }}</p>
          <p class="mb-0"><strong>Deadline:</strong> {{ goal.deadline.date }}</p>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No goals found.</p>
  {% endif %}

{% endblock %}

templates/goal/goalstage_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Goal Stage?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <button type="button" onclick="goBack()" class="btn btn-secondary">No, go back</button>
  </form>


  <script>
      function goBack() {
          window.history.back();
      }
  </script>
{% endblock %}

templates/goal/goalstage_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    {{ object|yesno:"Update, Create" }} goal stage
  </h1>
  <div class="left-right-margin-add" style="width: 50%">
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}